import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export type PlanDay = {
  dayIndex: number;
  dayEn: string;
  dayAr: string;
  date: string;
  platform: string;
  contentType: string;
  topic: string;
  topicAr?: string;
  caption: string;
  captionAr?: string;
  hashtags: string[];
  postingTime: string;
  postingTimeReason?: string;
  contentTips?: string;
  imagePromptHint?: string;
};

export type ContentPlan = {
  weekTheme: string;
  weekThemeAr: string;
  days: PlanDay[];
  weeklyStrategy?: string;
  expectedEngagement?: string;
};

export type Company = {
  id: string;
  name: string;
  name_ar?: string | null;
  brand_colors?: string[] | null;
};

function dayLabel(d: PlanDay, lang: "en" | "ar") {
  return lang === "ar" ? d.dayAr : d.dayEn;
}

function topicLabel(d: PlanDay, lang: "en" | "ar") {
  return lang === "ar" && d.topicAr ? d.topicAr : d.topic;
}

function captionLabel(d: PlanDay, lang: "en" | "ar") {
  return lang === "ar" && d.captionAr ? d.captionAr : d.caption;
}

function companyLabel(company: Company, lang: "en" | "ar") {
  return lang === "ar" && company.name_ar ? company.name_ar : company.name;
}

function themeLabel(plan: ContentPlan, lang: "en" | "ar") {
  return lang === "ar" && plan.weekThemeAr ? plan.weekThemeAr : plan.weekTheme;
}

function renderDayPage(d: PlanDay, lang: "en" | "ar", company: Company, plan: ContentPlan, brandColor: string): string {
  const dir = lang === "ar" ? "rtl" : "ltr";
  const labels = lang === "ar"
    ? { platform: "المنصة", type: "النوع", time: "وقت النشر", topic: "الموضوع", caption: "النص", hashtags: "الهاشتاقات", tips: "نصائح", generatedBy: "تم الإنشاء بواسطة نواة AI" }
    : { platform: "Platform", type: "Content Type", time: "Best Time", topic: "Topic", caption: "Caption", hashtags: "Hashtags", tips: "Content Tips", generatedBy: "Generated by Nawaa AI" };

  return `
    <div style="width: 900px; min-height: 580px; padding: 48px; background: #F8FBF8; color: #0A1F0F; font-family: 'Cairo', 'Plus Jakarta Sans', sans-serif; font-size: 16px; line-height: 1.6; direction: ${dir}; box-sizing: border-box;">
      <!-- Header -->
      <div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid ${brandColor}; padding-bottom: 16px; margin-bottom: 28px;">
        <div>
          <h1 style="font-size: 28px; color: ${brandColor}; margin: 0; font-weight: 800;">نواة | Nawaa AI</h1>
          <p style="margin: 4px 0 0; color: #5A8A6A; font-size: 15px;">${companyLabel(company, lang)} — ${themeLabel(plan, lang)}</p>
        </div>
        <div style="text-align: ${lang === "ar" ? "left" : "right"};">
          <p style="margin: 0; color: #004D26; font-size: 22px; font-weight: 700;">${dayLabel(d, lang)}</p>
          <p style="margin: 2px 0 0; color: #5A8A6A; font-size: 14px;">${d.date}</p>
        </div>
      </div>

      <!-- Platform + Time row -->
      <div style="display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap;">
        <div style="background: white; border: 2px solid #D4EBD9; border-radius: 12px; padding: 12px 20px; flex: 1; min-width: 180px;">
          <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600;">${labels.platform}</p>
          <p style="margin: 4px 0 0; font-size: 18px; color: #004D26; font-weight: 700;">${d.platform}</p>
        </div>
        <div style="background: white; border: 2px solid #D4EBD9; border-radius: 12px; padding: 12px 20px; flex: 1; min-width: 180px;">
          <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600;">${labels.type}</p>
          <p style="margin: 4px 0 0; font-size: 18px; color: #004D26; font-weight: 700;">${d.contentType}</p>
        </div>
        <div style="background: white; border: 2px solid #D4EBD9; border-radius: 12px; padding: 12px 20px; flex: 1; min-width: 180px;">
          <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600;">${labels.time}</p>
          <p style="margin: 4px 0 0; font-size: 18px; color: ${brandColor}; font-weight: 700;">${d.postingTime}</p>
          ${d.postingTimeReason ? `<p style="margin: 2px 0 0; font-size: 11px; color: #5A8A6A;">${d.postingTimeReason}</p>` : ""}
        </div>
      </div>

      <!-- Topic -->
      <div style="background: white; border: 2px solid #D4EBD9; border-radius: 16px; padding: 20px; margin-bottom: 20px;">
        <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600; margin-bottom: 6px;">${labels.topic}</p>
        <p style="margin: 0; font-size: 22px; color: #004D26; font-weight: 700;">${topicLabel(d, lang)}</p>
      </div>

      <!-- Caption -->
      <div style="background: white; border: 2px solid #D4EBD9; border-radius: 16px; padding: 20px; margin-bottom: 20px;">
        <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600; margin-bottom: 6px;">${labels.caption}</p>
        <p style="margin: 0; font-size: 15px; color: #0A1F0F; line-height: 1.7; white-space: pre-wrap;">${captionLabel(d, lang)}</p>
      </div>

      <!-- Hashtags -->
      <div style="background: white; border: 2px solid #D4EBD9; border-radius: 16px; padding: 16px 20px; margin-bottom: 20px;">
        <p style="margin: 0; font-size: 13px; color: #5A8A6A; font-weight: 600; margin-bottom: 8px;">${labels.hashtags}</p>
        <div style="display: flex; flex-wrap: wrap; gap: 8px;">
          ${(d.hashtags ?? []).map(tag => `<span style="display: inline-block; background: #F0F7F2; border: 1px solid #D4EBD9; border-radius: 8px; padding: 6px 14px; font-size: 14px; color: #006C35; font-weight: 600;">${tag}</span>`).join("")}
        </div>
      </div>

      ${d.contentTips ? `
      <!-- Tips -->
      <div style="background: #F0F7F2; border: 2px solid #C9A84C; border-radius: 16px; padding: 16px 20px;">
        <p style="margin: 0; font-size: 13px; color: #C9A84C; font-weight: 600; margin-bottom: 4px;">${labels.tips}</p>
        <p style="margin: 0; font-size: 14px; color: #0A1F0F;">${d.contentTips}</p>
      </div>
      ` : ""}

      <!-- Footer -->
      <div style="margin-top: 24px; padding-top: 12px; border-top: 2px solid #D4EBD9; font-size: 12px; color: #5A8A6A; display: flex; justify-content: space-between;">
        <span>${labels.generatedBy}</span>
        <span>${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-US")}</span>
      </div>
    </div>
  `;
}

export async function exportPlanToPDF(
  plan: ContentPlan,
  company: Company,
  outputLanguage: "en" | "ar" = "ar"
): Promise<void> {
  const brandColor = company.brand_colors?.[0] || "#006C35";
  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const days = plan.days ?? [];
  if (days.length === 0) throw new Error("No days in plan");

  for (let i = 0; i < days.length; i++) {
    if (i > 0) pdf.addPage();

    const div = document.createElement("div");
    div.style.cssText = `position: fixed; left: -9999px; top: 0;`;
    div.innerHTML = renderDayPage(days[i], outputLanguage, company, plan, brandColor);
    document.body.appendChild(div);

    try {
      const canvas = await html2canvas(div, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#F8FBF8",
        logging: false,
      });
      const imgData = canvas.toDataURL("image/png");
      const pdfW = pdf.internal.pageSize.getWidth();
      const pdfH = pdf.internal.pageSize.getHeight();
      const ratio = Math.min(pdfW / canvas.width, pdfH / canvas.height) * 0.95;
      const w = canvas.width * ratio;
      const h = canvas.height * ratio;
      pdf.addImage(imgData, "PNG", (pdfW - w) / 2, (pdfH - h) / 2, w, h);
    } finally {
      document.body.removeChild(div);
    }
  }

  const filename = `NawaaAI-${(company.name || "Plan").replace(/\s+/g, "-")}-Week-${days[0]?.date ?? "plan"}.pdf`;
  pdf.save(filename);
}
