import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export type PlanDay = {
  dayIndex: number;
  dayEn: string;
  dayAr: string;
  date: string;
  platform: string;
  contentType: string;
  topic: string;
  topicAr?: string;
  caption: string;
  captionAr?: string;
  hashtags: string[];
  postingTime: string;
  postingTimeReason?: string;
  contentTips?: string;
  imagePromptHint?: string;
};

export type ContentPlan = {
  weekTheme: string;
  weekThemeAr: string;
  days: PlanDay[];
  weeklyStrategy?: string;
  expectedEngagement?: string;
};

export type Company = {
  id: string;
  name: string;
  name_ar?: string | null;
  brand_colors?: string[] | null;
};

const C = {
  green: "#23ab7e",
  greenDark: "#1a8a64",
  purple: "#8054b8",
  pink: "#e67af3",
  teal: "#2dd4a0",
  lavender: "#c4a8e8",
  mint: "#a6ffea",
  dark: "#1a1d2e",
  gray: "#2d3142",
  muted: "#8f96a3",
  light: "#f4f6f8",
  border: "#e8eaef",
  white: "#ffffff",
};

const DAY_ACCENTS = [C.green, C.purple, C.pink, C.teal, C.lavender, "#f5c6fa", C.mint];

function dayLabel(d: PlanDay, lang: "en" | "ar") { return lang === "ar" ? d.dayAr : d.dayEn; }
function topicLabel(d: PlanDay, lang: "en" | "ar") { return lang === "ar" && d.topicAr ? d.topicAr : d.topic; }
function captionLabel(d: PlanDay, lang: "en" | "ar") { return lang === "ar" && d.captionAr ? d.captionAr : d.caption; }
function companyLabel(company: Company, lang: "en" | "ar") { return lang === "ar" && company.name_ar ? company.name_ar : company.name; }
function themeLabel(plan: ContentPlan, lang: "en" | "ar") { return lang === "ar" && plan.weekThemeAr ? plan.weekThemeAr : plan.weekTheme; }

// Font family for Arabic — Cairo first (best html2canvas compatibility), then system Arabic fonts
const AR_FONT = "'Cairo', 'Tahoma', 'Arial', sans-serif";
const EN_FONT = "'Outfit', 'Plus Jakarta Sans', 'Segoe UI', sans-serif";

function baseStyle(lang: "en" | "ar") {
  const dir = lang === "ar" ? "rtl" : "ltr";
  const fontFamily = lang === "ar" ? AR_FONT : EN_FONT;
  return `direction: ${dir}; font-family: ${fontFamily}; text-align: ${lang === "ar" ? "right" : "left"};`;
}

// Wrap text that might be Arabic with proper attributes
function t(text: string, lang: "en" | "ar") {
  if (lang !== "ar") return text;
  return `<span dir="rtl" lang="ar" style="font-family: ${AR_FONT}; direction: rtl;">${text}</span>`;
}

/* ═══════════════════════════════════
   COVER PAGE
   ═══════════════════════════════════ */
function renderCoverPage(plan: ContentPlan, company: Company, lang: "en" | "ar"): string {
  const days = plan.days ?? [];
  const dateRange = days.length >= 2 ? `${days[0].date} — ${days[days.length - 1].date}` : days[0]?.date ?? "";
  const platforms = [...new Set(days.map(d => d.platform))];
  const l = lang === "ar"
    ? { weekly: "خطة المحتوى الأسبوعية", theme: "موضوع الأسبوع", platforms: "منصة", days: "يوم", generated: "تم الإنشاء بواسطة", poweredBy: "مدعوم بالذكاء الاصطناعي", vision: "رؤية 2030" }
    : { weekly: "Weekly Content Plan", theme: "Week Theme", platforms: "Platforms", days: "Days", generated: "Generated by", poweredBy: "Powered by AI", vision: "Vision 2030" };

  return `
    <div style="width: 900px; height: 600px; background: linear-gradient(135deg, ${C.green} 0%, ${C.greenDark} 30%, ${C.purple} 70%, #a45dd4 100%); color: white; ${baseStyle(lang)} box-sizing: border-box; position: relative; overflow: hidden;">
      <div style="position: absolute; top: -80px; right: -80px; width: 300px; height: 300px; border-radius: 50%; background: rgba(255,255,255,0.07);"></div>
      <div style="position: absolute; bottom: -60px; left: -60px; width: 250px; height: 250px; border-radius: 50%; background: rgba(255,255,255,0.05);"></div>
      <div style="position: absolute; top: 35%; left: 55%; width: 200px; height: 200px; border-radius: 50%; background: rgba(166,255,234,0.06);"></div>

      <div style="position: relative; z-index: 2; padding: 56px 64px; height: 100%; display: flex; flex-direction: column; justify-content: space-between;">
        <div style="display: flex; align-items: center; gap: 16px;">
          <div style="width: 52px; height: 52px; background: rgba(255,255,255,0.15); border-radius: 14px; border: 1px solid rgba(255,255,255,0.2); display: flex; align-items: center; justify-content: center; font-size: 24px; font-weight: 900; color: ${C.mint};">N</div>
          <span style="font-size: 30px; font-weight: 800; letter-spacing: -0.5px;">Nawaa AI</span>
        </div>

        <div>
          <p style="font-size: 15px; font-weight: 600; color: rgba(255,255,255,0.5); text-transform: uppercase; letter-spacing: 4px; margin: 0 0 16px;">${t(l.weekly, lang)}</p>
          <p style="font-size: 48px; font-weight: 900; margin: 0 0 10px; line-height: 1.15; letter-spacing: -1px;">${t(companyLabel(company, lang), lang)}</p>
          <p style="font-size: 20px; color: rgba(255,255,255,0.65); margin: 0 0 36px;">${dateRange}</p>
          <div style="display: inline-block; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.18); border-radius: 16px; padding: 16px 28px;">
            <p style="margin: 0 0 6px; font-size: 11px; font-weight: 700; color: ${C.mint}; text-transform: uppercase; letter-spacing: 2px;">${t(l.theme, lang)}</p>
            <p style="margin: 0; font-size: 22px; font-weight: 700;">${t(themeLabel(plan, lang), lang)}</p>
          </div>
        </div>

        <div style="display: flex; gap: 40px; align-items: flex-end;">
          <div>
            <p style="margin: 0; font-size: 44px; font-weight: 900;">${days.length}</p>
            <p style="margin: 0; font-size: 14px; color: rgba(255,255,255,0.5);">${t(l.days, lang)}</p>
          </div>
          <div>
            <p style="margin: 0; font-size: 44px; font-weight: 900;">${platforms.length}</p>
            <p style="margin: 0; font-size: 14px; color: rgba(255,255,255,0.5);">${t(l.platforms, lang)}</p>
          </div>
          <div style="flex: 1;"></div>
          <div style="text-align: ${lang === "ar" ? "left" : "right"};">
            <p style="margin: 0; font-size: 12px; color: rgba(255,255,255,0.4);">${t(l.generated, lang)}</p>
            <p style="margin: 4px 0 0; font-size: 15px; font-weight: 700; color: ${C.mint};">Nawaa AI — ${t(l.poweredBy, lang)}</p>
            <p style="margin: 4px 0 0; font-size: 11px; color: rgba(255,255,255,0.3);">${t(l.vision, lang)}</p>
          </div>
        </div>
      </div>
    </div>
  `;
}

/* ═══════════════════════════════════
   DAY PAGE
   ═══════════════════════════════════ */
function renderDayPage(d: PlanDay, lang: "en" | "ar", company: Company, plan: ContentPlan, dayIdx: number): string {
  const accent = DAY_ACCENTS[dayIdx % DAY_ACCENTS.length];
  const l = lang === "ar"
    ? { platform: "المنصة", type: "النوع", time: "وقت النشر", topic: "الموضوع", caption: "النص", hashtags: "الهاشتاقات", tips: "نصائح", imageIdea: "فكرة الصورة", day: "اليوم", timeReason: "السبب" }
    : { platform: "Platform", type: "Content Type", time: "Best Time", topic: "Topic", caption: "Caption", hashtags: "Hashtags", tips: "Content Tips", imageIdea: "Image Idea", day: "Day", timeReason: "Why this time" };

  return `
    <div style="width: 900px; min-height: 580px; padding: 40px 48px; background: ${C.white}; color: ${C.dark}; ${baseStyle(lang)} font-size: 14px; line-height: 1.6; box-sizing: border-box;">
      <div style="height: 5px; border-radius: 3px; background: linear-gradient(90deg, ${accent}, ${accent}44); margin-bottom: 24px;"></div>

      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 22px;">
        <div style="display: flex; align-items: center; gap: 14px;">
          <div style="width: 48px; height: 48px; background: ${accent}; border-radius: 14px; display: flex; align-items: center; justify-content: center; color: white; font-size: 22px; font-weight: 900;">${dayIdx + 1}</div>
          <div>
            <p style="font-size: 26px; color: ${C.dark}; margin: 0; font-weight: 800;">${t(dayLabel(d, lang), lang)}</p>
            <p style="margin: 2px 0 0; color: ${C.muted}; font-size: 13px;">${d.date} | ${t(companyLabel(company, lang), lang)}</p>
          </div>
        </div>
        <div style="color: ${C.muted}; font-size: 11px;">
          <span style="color: ${accent}; font-weight: 700;">Nawaa AI</span> | ${t(l.day, lang)} ${dayIdx + 1}/7
        </div>
      </div>

      <div style="display: flex; gap: 10px; margin-bottom: 18px; flex-wrap: wrap;">
        ${[
          { label: l.platform, value: d.platform, clr: accent },
          { label: l.type, value: d.contentType, clr: C.purple },
          { label: l.time, value: d.postingTime, clr: C.green },
        ].map(item => `
          <div style="background: ${item.clr}0a; border: 1.5px solid ${item.clr}22; border-radius: 12px; padding: 10px 18px; flex: 1; min-width: 150px;">
            <p style="margin: 0; font-size: 10px; color: ${item.clr}; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px;">${item.label}</p>
            <p style="margin: 3px 0 0; font-size: 17px; color: ${C.dark}; font-weight: 700;">${item.value}</p>
          </div>
        `).join("")}
      </div>

      <div style="background: ${accent}0a; border: 1.5px solid ${accent}22; border-radius: 14px; padding: 14px 20px; margin-bottom: 16px;">
        <p style="margin: 0; font-size: 10px; color: ${accent}; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 3px;">${t(l.topic, lang)}</p>
        <p style="margin: 0; font-size: 19px; color: ${C.dark}; font-weight: 800;">${t(topicLabel(d, lang), lang)}</p>
      </div>

      <div style="background: ${C.light}; border: 1.5px solid ${C.border}; border-radius: 14px; padding: 18px 20px; margin-bottom: 16px;">
        <p style="margin: 0; font-size: 10px; color: ${C.purple}; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 8px;">${t(l.caption, lang)}</p>
        <p style="margin: 0; font-size: 13px; color: ${C.gray}; line-height: 1.85; white-space: pre-wrap;">${t(captionLabel(d, lang), lang)}</p>
      </div>

      <div style="margin-bottom: 14px;">
        <p style="margin: 0 0 8px; font-size: 10px; color: ${C.purple}; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px;">${t(l.hashtags, lang)}</p>
        <div style="display: flex; flex-wrap: wrap; gap: 6px;">
          ${(d.hashtags ?? []).map((tag, i) => {
            const tc = DAY_ACCENTS[i % DAY_ACCENTS.length];
            return `<span dir="${lang === "ar" ? "rtl" : "ltr"}" style="display: inline-block; background: ${tc}14; border: 1px solid ${tc}28; border-radius: 8px; padding: 5px 14px; font-size: 12px; color: ${tc}; font-weight: 700; font-family: ${lang === "ar" ? AR_FONT : EN_FONT};">${tag}</span>`;
          }).join("")}
        </div>
      </div>

      ${d.contentTips ? `
      <div style="background: ${C.pink}0a; border: 1.5px solid ${C.pink}22; border-radius: 12px; padding: 12px 18px; margin-bottom: 12px;">
        <p style="margin: 0; font-size: 10px; color: ${C.pink}; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 3px;">${t(l.tips, lang)}</p>
        <p style="margin: 0; font-size: 12px; color: ${C.gray}; line-height: 1.7;">${t(d.contentTips, lang)}</p>
      </div>` : ""}

      ${d.imagePromptHint ? `
      <div style="background: ${C.purple}0a; border: 1.5px solid ${C.purple}22; border-radius: 12px; padding: 12px 18px; margin-bottom: 12px;">
        <p style="margin: 0; font-size: 10px; color: ${C.purple}; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 3px;">${t(l.imageIdea, lang)}</p>
        <p style="margin: 0; font-size: 12px; color: ${C.gray}; line-height: 1.7;">${t(d.imagePromptHint, lang)}</p>
      </div>` : ""}

      ${d.postingTimeReason ? `
      <div style="background: ${C.green}08; border-radius: 10px; padding: 10px 16px;">
        <p style="margin: 0; font-size: 11px; color: ${C.green};"><span style="font-weight: 700;">${t(l.timeReason, lang)}:</span> ${t(d.postingTimeReason, lang)}</p>
      </div>` : ""}

      <div style="margin-top: 18px; padding-top: 10px; border-top: 1.5px solid ${C.border}; font-size: 10px; color: ${C.muted}; display: flex; justify-content: space-between;">
        <span>Nawaa AI | ${t(companyLabel(company, lang), lang)}</span>
        <span>${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-US")}</span>
      </div>
    </div>
  `;
}

/* ═══════════════════════════════════
   CONCLUSION PAGE
   ═══════════════════════════════════ */
function renderConclusionPage(plan: ContentPlan, company: Company, lang: "en" | "ar"): string {
  const days = plan.days ?? [];
  const platforms = [...new Set(days.map(d => d.platform))];
  const totalHashtags = days.reduce((sum, d) => sum + (d.hashtags?.length ?? 0), 0);
  const l = lang === "ar"
    ? { summary: "ملخص الخطة", strategy: "الاستراتيجية الأسبوعية", engagement: "التفاعل المتوقع", posts: "منشور", plat: "منصة", hash: "هاشتاق", ready: "خطتك جاهزة للتنفيذ!", readyDesc: "ابدأ بنشر المحتوى حسب الجدول المقترح لتحقيق أفضل نتائج. حظا موفقا!", generated: "تم الإنشاء بواسطة نواة AI", vision: "رؤية 2030 — حيث تنمو العلامات السعودية بالذكاء الاصطناعي" }
    : { summary: "Plan Summary", strategy: "Weekly Strategy", engagement: "Expected Engagement", posts: "Posts", plat: "Platforms", hash: "Hashtags", ready: "Your Plan is Ready!", readyDesc: "Start posting content according to the suggested schedule for best results. Good luck!", generated: "Generated by Nawaa AI", vision: "Vision 2030 — Where Saudi brands grow with AI" };

  return `
    <div style="width: 900px; height: 600px; background: ${C.white}; color: ${C.dark}; ${baseStyle(lang)} box-sizing: border-box; position: relative; overflow: hidden;">
      <div style="height: 5px; background: linear-gradient(90deg, ${C.green}, ${C.purple}, ${C.pink});"></div>

      <div style="padding: 44px 56px; height: calc(100% - 5px); display: flex; flex-direction: column; justify-content: space-between;">
        <div style="display: flex; align-items: center; gap: 14px; margin-bottom: 28px;">
          <div style="width: 44px; height: 44px; background: linear-gradient(135deg, ${C.green}, ${C.purple}); border-radius: 12px; display: flex; align-items: center; justify-content: center; color: white; font-size: 20px; font-weight: 900;">N</div>
          <span style="font-size: 22px; font-weight: 800; color: ${C.dark};">Nawaa AI</span>
          <span style="font-size: 14px; color: ${C.muted};">|</span>
          <span style="font-size: 14px; color: ${C.muted};">${t(companyLabel(company, lang), lang)}</span>
        </div>

        <div>
          <p style="font-size: 34px; font-weight: 900; color: ${C.dark}; margin: 0 0 6px;">${t(l.summary, lang)}</p>
          <p style="font-size: 16px; color: ${C.muted}; margin: 0;">${t(themeLabel(plan, lang), lang)}</p>
        </div>

        <div style="display: flex; gap: 16px; margin: 20px 0;">
          ${[
            { value: days.length, label: l.posts, clr: C.green },
            { value: platforms.length, label: l.plat, clr: C.purple },
            { value: totalHashtags, label: l.hash, clr: C.pink },
          ].map(s => `
            <div style="flex: 1; background: ${s.clr}0a; border: 1.5px solid ${s.clr}22; border-radius: 18px; padding: 22px; text-align: center;">
              <p style="margin: 0; font-size: 40px; font-weight: 900; color: ${s.clr};">${s.value}</p>
              <p style="margin: 4px 0 0; font-size: 13px; font-weight: 600; color: ${C.muted};">${s.label}</p>
            </div>
          `).join("")}
        </div>

        <div style="display: flex; gap: 14px;">
          ${plan.weeklyStrategy ? `
          <div style="flex: 1; background: ${C.light}; border: 1.5px solid ${C.border}; border-radius: 14px; padding: 18px;">
            <p style="margin: 0 0 6px; font-size: 10px; font-weight: 700; color: ${C.purple}; text-transform: uppercase; letter-spacing: 1.5px;">${t(l.strategy, lang)}</p>
            <p style="margin: 0; font-size: 13px; color: ${C.gray}; line-height: 1.7;">${t(plan.weeklyStrategy ?? "", lang)}</p>
          </div>` : ""}
          ${plan.expectedEngagement ? `
          <div style="flex: 1; background: ${C.light}; border: 1.5px solid ${C.border}; border-radius: 14px; padding: 18px;">
            <p style="margin: 0 0 6px; font-size: 10px; font-weight: 700; color: ${C.green}; text-transform: uppercase; letter-spacing: 1.5px;">${t(l.engagement, lang)}</p>
            <p style="margin: 0; font-size: 13px; color: ${C.gray}; line-height: 1.7;">${t(plan.expectedEngagement ?? "", lang)}</p>
          </div>` : ""}
        </div>

        <div style="background: linear-gradient(135deg, ${C.green}0c, ${C.purple}0c); border: 1.5px solid ${C.green}22; border-radius: 18px; padding: 22px 28px; display: flex; align-items: center; gap: 18px;">
          <div style="width: 50px; height: 50px; background: linear-gradient(135deg, ${C.green}, ${C.purple}); border-radius: 14px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; color: white; font-size: 22px; font-weight: 900;">!</div>
          <div>
            <p style="margin: 0; font-size: 20px; font-weight: 800; color: ${C.dark};">${t(l.ready, lang)}</p>
            <p style="margin: 4px 0 0; font-size: 13px; color: ${C.muted};">${t(l.readyDesc, lang)}</p>
          </div>
        </div>

        <div style="display: flex; justify-content: space-between; align-items: center; padding-top: 14px; border-top: 1.5px solid ${C.border};">
          <div>
            <p style="margin: 0; font-size: 12px; font-weight: 700; color: ${C.green};">${t(l.generated, lang)}</p>
            <p style="margin: 2px 0 0; font-size: 10px; color: ${C.muted};">${t(l.vision, lang)}</p>
          </div>
          <p style="margin: 0; font-size: 10px; color: ${C.muted};">${new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-US")}</p>
        </div>
      </div>
    </div>
  `;
}

/* ═══════════════════════════════════
   EXPORT FUNCTION
   ═══════════════════════════════════ */
export async function exportPlanToPDF(
  plan: ContentPlan,
  company: Company,
  outputLanguage: "en" | "ar" = "ar"
): Promise<void> {
  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const days = plan.days ?? [];
  if (days.length === 0) throw new Error("No days in plan");

  // Preload all fonts
  await document.fonts.ready;
  try {
    await Promise.all([
      document.fonts.load("400 16px 'Cairo'"),
      document.fonts.load("700 16px 'Cairo'"),
      document.fonts.load("900 16px 'Cairo'"),
      document.fonts.load("400 16px 'IBM Plex Sans Arabic'"),
      document.fonts.load("700 16px 'IBM Plex Sans Arabic'"),
      document.fonts.load("400 16px 'Outfit'"),
      document.fonts.load("700 16px 'Outfit'"),
    ]);
  } catch { /* continue */ }

  // Show loading overlay so user doesn't see render divs
  const overlay = document.createElement("div");
  overlay.style.cssText = `position: fixed; inset: 0; z-index: 99999; background: rgba(255,255,255,0.92); backdrop-filter: blur(8px); display: flex; align-items: center; justify-content: center;`;
  overlay.innerHTML = `<div style="text-align: center; font-family: 'Cairo','Outfit',sans-serif;">
    <div style="width: 64px; height: 64px; margin: 0 auto 16px; border-radius: 16px; background: linear-gradient(135deg, #23ab7e, #8054b8); display: flex; align-items: center; justify-content: center; color: white; font-size: 28px; font-weight: 900; animation: spin 1.5s linear infinite;">N</div>
    <p style="font-size: 18px; font-weight: 700; color: #2d3142; margin: 0 0 6px;">${outputLanguage === "ar" ? "جارٍ تصدير PDF..." : "Exporting PDF..."}</p>
    <p style="font-size: 14px; color: #8f96a3; margin: 0;">${outputLanguage === "ar" ? "لحظة واحدة" : "Just a moment"}</p>
    <style>@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }</style>
  </div>`;
  document.body.appendChild(overlay);

  async function renderPage(html: string) {
    const wrapper = document.createElement("div");
    // Render VISIBLE in the document flow so browser fully shapes Arabic text
    // Behind the loading overlay (z-index: 99998 < overlay's 99999)
    wrapper.style.cssText = `position: fixed; top: 0; left: 0; z-index: 99998; pointer-events: none; opacity: 0.01;`;
    if (outputLanguage === "ar") {
      wrapper.setAttribute("dir", "rtl");
      wrapper.setAttribute("lang", "ar");
    }
    wrapper.innerHTML = html;
    document.body.appendChild(wrapper);

    // Wait for browser to fully layout, shape glyphs, and paint
    await new Promise(r => setTimeout(r, 500));
    // Force a layout recalculation
    const target = wrapper.firstElementChild as HTMLElement;
    void target.offsetHeight;
    await new Promise(r => setTimeout(r, 200));

    try {
      const canvas = await html2canvas(target, {
        scale: 1.5,
        useCORS: true,
        backgroundColor: null,
        logging: false,
        allowTaint: true,
        onclone: (clonedDoc) => {
          // Ensure cloned document also has proper Arabic attributes
          const clonedEl = clonedDoc.querySelector("[dir]") as HTMLElement;
          if (clonedEl && outputLanguage === "ar") {
            clonedEl.style.direction = "rtl";
            clonedEl.lang = "ar";
          }
        },
      });
      const imgData = canvas.toDataURL("image/jpeg", 0.88);
      const pdfW = pdf.internal.pageSize.getWidth();
      const pdfH = pdf.internal.pageSize.getHeight();
      const ratio = Math.min(pdfW / canvas.width, pdfH / canvas.height) * 0.97;
      const w = canvas.width * ratio;
      const h = canvas.height * ratio;
      pdf.addImage(imgData, "JPEG", (pdfW - w) / 2, (pdfH - h) / 2, w, h);
    } finally {
      document.body.removeChild(wrapper);
    }
  }

  // Page 1: Cover
  await renderPage(renderCoverPage(plan, company, outputLanguage));

  // Pages 2-8: Days
  for (let i = 0; i < days.length; i++) {
    pdf.addPage();
    await renderPage(renderDayPage(days[i], outputLanguage, company, plan, i));
  }

  // Final page: Conclusion
  pdf.addPage();
  await renderPage(renderConclusionPage(plan, company, outputLanguage));

  // Remove loading overlay
  try { document.body.removeChild(overlay); } catch { /* already removed */ }

  const filename = `NawaaAI-${(company.name || "Plan").replace(/\s+/g, "-")}-Week-${days[0]?.date ?? "plan"}.pdf`;
  pdf.save(filename);
}
